In [1]:
import numpy as np
from scipy.optimize import linprog

costs = np.array([[27, 36, 35, 31, 29],
                  [22, 23, 26, 32, 35],
                  [35, 42, 38, 32, 39]])

supply = np.array([250, 200, 200])
demand = np.array([120, 130, 100, 160, 140])

# Розгортаємо матрицю вартостей для використання в функції лінійного програмування
c = costs.flatten()

# Матриця обмежень (A_eq) та права частина рівняння (b_eq)
A_eq = np.zeros((len(supply) + len(demand), len(c)))
b_eq = np.zeros(len(supply) + len(demand))

# Додаємо обмеження на постачання та на попит
for i in range(len(supply)):
    A_eq[i, i * len(demand):(i + 1) * len(demand)] = 1
    b_eq[i] = supply[i]

for j in range(len(demand)):
    A_eq[len(supply) + j, j:len(c):len(demand)] = 1
    b_eq[len(supply) + j] = demand[j]

# Розв'язуємо задачу лінійного програмування
result = linprog(c, A_eq=A_eq, b_eq=b_eq, method='highs')
solution = result.x.reshape(costs.shape)

print("Оптимальний план:")
print(solution)
print("\nTotal Cost:", result.fun)



Оптимальний план:
[[110.   0.   0.   0. 140.]
 [ 10. 130.  60.   0.   0.]
 [  0.   0.  40. 160.   0.]]

Total Cost: 18440.0
