In [155]:
import numpy as np

def saddle_points(matrix):
    matrix = np.array(matrix)
    row_mins = np.min(matrix, axis=1)
    row_maxs = np.max(matrix, axis=1)
    col_mins = np.min(matrix, axis=0)
    col_maxs = np.max(matrix, axis=0)

    saddle_indices = np.argwhere(
        (matrix == row_mins[:, np.newaxis]) & (matrix == col_maxs) |
        (matrix == row_maxs[:, np.newaxis]) & (matrix == col_mins)
    )
    
    saddlePoints = set(map(tuple, saddle_indices))

    print("Сідлові точки та їх значення:")
    for point in saddlePoints:
             print(f"Ціна гри - елемент на позиції {point}: {matrix[point]}")
    
    return saddlePoints



def CheckSaddlePoint(matrix, maxi, mini):
    if maxi != mini:
        return print("Розв'язку в чистих стратегіях немає")
    
    saddlePoints = saddle_points(matrix)

    if len(saddlePoints) == 0:
        print("Розв'язку в чистих стратегіях немає")
    else:
        print(saddlePoints)


Задача 5
	    В1	    В2	    В3	    В4
А1	    0,8 	0,6	    0,2	    -0,8
А2	    -0,8	0,9 	-0,4	0,5
А3	    1,7	    0,5	    0,3	    0,6


In [156]:
matrix = [
    [0.8, 0.6, 0.2, -0.8],
    [-0.8, 0.9, -0.4, 0.5],
    [1.7, 0.5, 0.3, 0.6],
]

print(matrix)

[[0.8, 0.6, 0.2, -0.8], [-0.8, 0.9, -0.4, 0.5], [1.7, 0.5, 0.3, 0.6]]


Нижня ціна гри

In [157]:
minA = np.min(matrix, axis = 1)
maxA = max(minA)

print(minA)
print(maxA)

[-0.8 -0.8  0.3]
0.3


Верхня ціна гри

In [158]:
maxB = np.max(matrix, axis = 0)
minB = min(maxB)

print(maxB)
print(minB)

[1.7 0.9 0.3 0.6]
0.3


In [159]:
CheckSaddlePoint(matrix, maxA, minB)

Сідлові точки та їх значення:
Елемент на позиції (2, 2): 0.3
{(2, 2)}


Отже, стратегія 3(з індексом 2) є оптимальною

Сільськогосподарське підприємство вирощує картоплю. Площа ділянки картоплі становить 100 га. Господарство має договір з магазином, який гарантовано закупить всю картоплю по ціні 4 у.г.о . за 1 кг. При вирощуванні картоплі господарство може прийняти одне з трьох рішень, що розрізняються за сумою витрат на виробництво тощо про продукції:
A 1. Провести комплексну обробку рослин для запобігання ураження бур'янами, шкідниками і хворобами (витрати - 6 млн. У.г.о .). 
A 2. Провести часткову обробку рослин (витрати - 4 млн. У.г.о .). 
A 3. Чи не проводити обробку рослин (витрати - 2.5 млн. У.г.о .). 
Залежно від погодних умов, наявності та розвитку бур'янів, шкідників і хвороб можливі наступні ситуації: 
S 1. Умови для розвитку бур'янів, шкідників і хвороб несприятливі. 
S 2. Умови для розвитку бур'янів, шкідників і хвороб звичайні. 
S 3. Умови для розвитку бур'янів, шкідників і хвороб сприятливі.  
Значення врожайності картоплі (ц / га) залежно від рішень сільськогосподарського підприємства і розвитку бур'янів, шкідників і хвороб тощо і наведені в таблиці

	S1	S2	S3
A1	260	260	260
A2	255	200	145
A3	250	100	40

Визначте найбільш оптимальну стратегію підприємства і ціну гри. 

In [160]:
# Врожайність картоплі для кожної стратегії та умови
harvest_matrix = np.array([
    [260, 260, 260],
    [255, 200, 145],
    [250, 100, 40]
])
salary = 4
# Витрати на виробництво для кожної стратегії
costs = np.array([6, 4, 2.5])

# Розрахунок матриці виграшу
total_score = [[score * salary * 100 * 100 - cost * 1000000 for score, cost in zip(harvest_row, costs)] for harvest_row in zip(*harvest_matrix)]

transpose = [list(column) for column in zip(*total_score)]

print(transpose)


[[4400000.0, 4400000.0, 4400000.0], [6200000.0, 4000000.0, 1800000.0], [7500000.0, 1500000.0, -900000.0]]


In [161]:
min_A = np.min(transpose, axis = 1)
max_A = max(min_A)

print(min_A)
print(max_A)

[4400000. 1800000. -900000.]
4400000.0


In [162]:
max_B= np.max(transpose, axis = 1)
min_B = min(max_B)

print(max_B)
print(min_B)

[4400000. 6200000. 7500000.]
4400000.0


In [163]:
CheckSaddlePoint(transpose, max_A, min_B)

Сідлові точки та їх значення:
Елемент на позиції (0, 1): 4400000.0
Елемент на позиції (0, 2): 4400000.0
Елемент на позиції (0, 0): 4400000.0
{(0, 1), (0, 2), (0, 0)}


Отже, стратегія 1(з індексом 0) є оптимальною.